### ISSUE TITLE
Cannot access the admin pannel

### ISSUE THREAD

**Issue by InsertGoodNickname** [computernewb/collab-vm-server-1.2#13]
I was able to compile the collab-vm-server (and the other packages except for the dll) but everytime i try to access the admin panel it says: 
Error 404
The requested URL /admin/login was not found on this server.

When looking for the file in the http/admin folder I only see: admin.min.js config.html and index.html

Is there anyway to fix this?
Note: I'm using the latest release of xubuntu

**Comment by rikosaku** [comment]
You cannot use the admin/index.html file. For new builds admin/config.html
works. Probably some websocketpp stuff I don't know how to port up to the
latest version.

**Comment by InsertGoodNickname** [comment]
I see (I'll stick with the binary then). 

One more thing i would like to ask about. How would one connect to the vm. I have it all setup in the admin console, I just don't know how to connect to it through the web server.

**Comment by rikosaku** [comment]
In the js console do
```
multicollab("<IP>:<PORT>")
```

**Comment by dartzcn** [comment]
> One more thing i would like to ask about. How would one connect to the vm. I have it all setup in the admin console, I just don't know how to connect to it through the web server.

You can build the [collab-vm-web-app](https://github.com/computernewb/collab-vm-web-app) or you can go onto http://computernewb.com/collab-vm/ and do what rikosaku said. The instructions to build the collab-vm-web-app are in the description.

**Comment by dartzcn** [comment]
This should now be fixed. You can now go to /admin/ directly to login.

**Comment by Damijanmitrevskiboy** [comment]
hello i got banned from collab vm for being a bsod fag  how can i appeal my ban

**Comment by juliaszone** [comment]
> hello i got banned from collab vm for being a bsod fag how can i appeal my ban
you lost the game already

**Comment by 86dd** [comment]
and you lost the game already
> hello i got banned from collab vm for being a bsod fag how can i appeal my ban

**Comment by Undefishin** [comment]
> hello i got banned from collab vm for being a bsod fag how can i appeal my ban

why are you commenting on a nearly 4 year old issue lol

**Comment by bruhfromcollabvm** [comment]
> hello i got banned from collab vm for being a bsod fag how can i appeal my ban

by NOT being a bsodfriend
