### ISSUE TITLE
刘宾 您好

### ISSUE THREAD

**Issue by binbinlau** [computernewb/collab-vm-server-1.2#18]
刘宾 您好：

     感谢您对我公司的关注与信任！通过初试，我们认为您符合高级Java开发工程师的岗位要求，因此正式通知您来参加复试。

具体安排如下：

一、预约时间：2019年8月7号（周三）上午9:30， 如时间不方便请提前回复邮件改约时间

二、面试地址：北京市海淀区西三旗建材城东路16号中国工商银行北京数据中心

三、联系人：李女士（小姐姐）15801641024    衡露  13783517618

四、携带资料：请携带身份证及一份个人简历

五、乘车路线：地铁8号线育新站，D西南口出，转乘运通117、432、614路4站，硅谷小区站下车（ 不是旁边的工商银行哦）向东200米 即到，传达室登记后直接进主楼二层电梯口即可

如果对路线还不是很清楚，别犹豫，直接电联面试联系人，她会成为你的导航小助手。

**Comment by binbinlau** [comment]
尊敬的客户：

我是AWS技术支持工程师奇勋。很高兴能协助您的案例。

我了解到您的实例i-0c061203dce0a8417无法连接。

根据您的截图，我看到在开机过程中出现了核心相关的错误：

[    7.280388] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00007f00

使得开机过程未成功，因此您无法连上实例。
另外，我观察到在2019-08-15 15:58 UTC 之后实例的状态检查[1]就一直失败。此代表当时OS就出了问题，然而由于AWS技术支持无法得到实例内部资讯，我无法确认当时原因。您可参考实例状态检查的说明文件[2]以了解更多細節。

由于造成此内核错误的可能原因很多，需要更多资讯以判断问题。麻烦您提供以下资讯：

1. 想请问您在2019-08-15 15:58 UTC有作什么变动？例如，我观察到核心版本以非ami-0b500ef59d8335eee的预设版本。您是否升级了核心及其他变动？
2. 我请您参考夹带档案(修复实例.pdf)的步骤取得实例内的资料。依照步骤，将能在/mnt看到i-0c061203dce0a8417的资料。请使用以下"tar"命令将所有日志及fstab档案压缩成名为archive.tar.gz的档案:
          
    $ sudo tar -zcvf /tmp/archive.tar.gz /mnt/var/log /mnt/etc/fstab /mnt/etc/selinux/config
        
    麻烦将所有档案依照文末所附的上传方式[3]上传给我分析。/var/log内的日志包含更精确的错误讯息，而根据经验，有些时候/etc/fstab的挂载设定有误时可能导致核心错误。此外，也有见过跟selinux设定有关的案例，因此收集selinux设定档。

当能取得实例内的资料，您也可以开启新实例，转移资料，重新部署您的服务以暂时解决问题。

若您对以上有任何相关问题，欢迎回覆案例询问。我们将乐意协助您。


参考资料：
[1]StatusCheckFailed_Instance:
https://console.aws.amazon.com/cloudwatch/home?region=us-east-2#metricsV2:graph=~%28region~%27us-east-2~metrics~%28~%28~%27AWS*2fEC2~%27StatusCheckFailed_Instance~%27InstanceId~%27i-0c061203dce0a8417%29%29~period~900~stat~%27Sum~start~%272019-08-10T10*3a28*3a11Z~end~%272019-08-17T10*3a28*3a11Z%29 
  
  
  


[2] 实例的状态检查 - 状态检查的类型, https://docs.aws.amazon.com/zh_cn/AWSEC2/latest/UserGuide/monitoring-system-instance-status-check.html#types-of-instance-status-checks 
  
  
  

[3] 点击以下连结上传档案
AWS Support - S3 Uploader
https://aws-support-uploader.s3.amazonaws.com/uploader?account-id=965903677230&case-id=6362601481&expiration=1567249522&key=6165d1435602268c1a22f898a77058f4b92e27e4c8b969e4e1ba7d8067bbf19e 
  
  
  


To see the file named '修复实例.pdf' included with this correspondence, please use the case link given below the signature.

Best regards,

Wu E.
Amazon Web Services

**Comment by sparskakyl** [comment]
tunaman cube
