### ISSUE TITLE
VMWare and Virtual Box

### ISSUE THREAD

**Issue by matthall1998** [computernewb/collab-vm-server-1.2#3]
On the admin tab, to add a VM, VMWare and Virtual Box are unselectable! Only QEMU, I would like to use Virtual Box VMs. Thank you love the software and the website, want to thank you for your time!

**Comment by matthall1998** [comment]
Read the admin panel WIKI.

**Comment by dartzcn** [comment]
At this time, VirtualBox and VMWare are unsupported. Both of them are planned to be supported in CollabVM 2.0, which is currently in development.

-Dartz
