### ISSUE TITLE
make issue

### ISSUE THREAD

**Issue by RoxyBoxxy** [computernewb/collab-vm-server-1.2#33]
when ever i try and build it i get

Compiling targeting *nix
Building in release mode
make[1]: Entering directory '/root/collab-vm-server'
Generating src/Database/Config-odb.cxx using ODB
cc1plus: error: bad value (‘/dev/null’) for ‘-mtune=’ switch
cc1plus: note: valid arguments to ‘-mtune=’ switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 bonnell atom silvermont slm knl intel x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 btver1 btver2 generic
mk/Makedefs:111: recipe for target 'src/Database/Config-odb.cxx' failed
make[1]: *** [src/Database/Config-odb.cxx] Error 1
make[1]: Leaving directory '/root/collab-vm-server'
Makefile:56: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Mayank-1234-cmd** [comment]
Yep, getting same error. (gcc 7.5.0 ubuntu)
(edit: i don't have sudo also)

**Comment by yellows111** [comment]
ugh... ODB... why do you do this on everything but my testing enviroments?

**Comment by yellows111** [comment]
Try adding `-v` to the `$(ODB)` rules in /mk/Makedefs (assuming / is actually /*/collab-vm-server/)

**Comment by yellows111** [comment]
apparently the fix is to either recompile ODB or downgrade your gcc version to 7.3 (ugh... this works NORMALLY for me, but it's probably because I COMPILED odb manually with a custom 9.3 enviroment, which has worked for me with siding it with GCC 10.1.0)
```
sudo apt install gcc-7-base=7.3.0-16ubuntu3 cpp-7=7.3.0-16ubuntu3 gcc-7=7.3.0-16ubuntu3 libgcc-7-dev=7.3.0-16ubuntu3 libasan4=7.3.0-16ubuntu3 libubsan0=7.3.0-16ubuntu3 libcilkrts5=7.3.0-16ubuntu3  
sudo apt install g++-7=7.3.0-16ubuntu3 libstdc++-7-dev=7.3.0-16ubuntu3  
sudo ln -s /usr/bin/g++-7 /usr/bin/g++  
sudo ln -s /usr/bin/gcc-7 /usr/bin/gcc  
sudo ln -s /usr/bin/gcc /usr/bin/cc```

**Comment by modeco80** [comment]
Closing since #49 kills ODB dependency.
