### ISSUE TITLE
Feature request : Rate-limits

### ISSUE THREAD

**Issue by moeenio** [computernewb/collab-vm-server-1.2#37]
Please add a rate-limiting system, for chat messages and username changes. The chat keeps getting cluttered.

**Comment by yellows111** [comment]
We tried this before, it crashed the server last time we attempted this.

**Comment by moeenio** [comment]
Don't test things in production?

**Comment by ghost** [comment]
> 
> 
> Don't test things in production?

but dev on prod is the best way of testing software

**Comment by ghost** [comment]
> 
> 
> /s?

partially

**Comment by jessiejs** [comment]
Just don't run it on the main server when testing it, run it on an alternate server.

**Comment by modeco80** [comment]
you write in python

**Comment by moeenio** [comment]
??
