### ISSUE TITLE
Bug : If typing just before turn end, last typed key will be repeated

### ISSUE THREAD

**Issue by moeenio** [computernewb/collab-vm-server-1.2#39]
Steps to Reproduce :
1. Take a turn to control a VM
2. Start typing something just before the end of the turn
3. Keep typing until the turn ends
4. Notice that the last typed character will be typed repeatedly until another one is typed.

**Comment by modeco80** [comment]
This could be fixed by spam calling GuacVNCClient::HandleKey() for 0-the last X keysym but that might cause problems when resetting the VM when a turn ends

although that SHOULD have been fixed ages ago either way so maybe it won't break anything

**Comment by modeco80** [comment]
I may fix this in a 1.2.11 hotfix, idk tho.

**Comment by ctrlaltf2** [comment]
I think I know of a way to fix this since I did something similar for Let's Play (though the possible set of "keys" is smaller there). I'm gonna reopen and throw this on 1.3 because I'm getting tired of typing `sudoooooooooooooooooooooooo` by accident.

**Comment by modeco80** [comment]
Yet another "1.x codebase closing reopen if needed"
