### ISSUE TITLE
Where is the binary?

### ISSUE THREAD

**Issue by Mayank-1234-cmd** [computernewb/collab-vm-server-1.2#41]
When I run ./collab-vm-server [port] it says bash: ./collab-vm-server: Is a directory.
I can't find the binary either. How do I run the server?

**Comment by Mayank-1234-cmd** [comment]
I thought ./build_site.sh was it and now it just returns "ヾ(*ФωФ)βyё βyё☆彡" (http://34.122.158.93/)

**Comment by yellows111** [comment]
uhh, sorry for being late, was busy working on... nevermind, But if you've compiled collab-vm-server (by `make JPEG=1` or such) you should find the wanted file in (collab-vm-server directory/root)/`bin/collab-vm-server`.

**Comment by Mayank-1234-cmd** [comment]
oh thats why (i don't have root)

**Comment by modeco80** [comment]
Seems to be resolved..? closing
