### ISSUE TITLE
Add the ability to change internal VM name

### ISSUE THREAD

**Issue by ctrlaltf2** [computernewb/collab-vm-server-1.2#56]
Currently changing the VM ID/Name (e.g. "vm1") requires the use of an external sqlite db editor. This issue should address this and make it able to be changed (likely from the admin panel?). May require small client changes in the admin panel part.

**Comment by modeco80** [comment]
This would give me an excuse to rewrite *all* of the JSON code  (and i mean, ALL of it. the QMP client? yes. the godawful admin panel code? also yes.) to instead use Boost.JSON.

I think the way to handle renaming would maybe be to do something ala this in the JSON data:

```json
{
   "name": "vm1"
   "rename_to": "vmABC"
}
```
If the `rename_to` property is inside of the JSON sent to the server when it recieves that admin opcode, it'd know "ok you mean this VM" and then itd do the rename (re-sending some of the admin data so everything gets populated properly)

And yeah, this does mean someone's gonna have to touch the admin panel (I wish you well diving deep into the pits of hell :smile:)

**Comment by modeco80** [comment]
Not using 1.x anymore for 3.0, closing
