### ISSUE TITLE
HEY DARTZ WHY IS FTP2.COMPUTERNEWB.COM REDIRECT TO FTP.COLLABVM.ML

### ISSUE THREAD

**Issue by vacbedlover** [computernewb/collab-vm-server-1.2#7]
HEY DARTZ WHY IS FTP2.COMPUTERNEWB.COM REDIRECT TO FTP.COLLABVM.ML

**Comment by dartzcn** [comment]
Not sure what you mean by this.

**Comment by vacbedlover** [comment]
hey bdartz why did you take down ftp2.computernewb.com and make it display ftp.collabvm.ml instead?10.02.2019, 18:55, "Dartz" <notifications@github.com>:Not sure what you mean by this.

**Comment by dartzcn** [comment]
ftp.collabvm.ml is just displaying ftp.computernewb.com, as is ftp2.computernewb.com.

To login to ftp2.computernewb.com, replace "anon" with "anon2" as the username.
