### ISSUE TITLE
Error "srcDatabaseConfig.h" when command "odb -d sqlite -s -q src\Database\Config.h src\Database\VMSettings.h" is run

### ISSUE THREAD

**Issue by JakeTrock** [computernewb/collab-vm-server-1.2#8]
I got this error after following instructions on ubuntu server 18.04

**Comment by dartzcn** [comment]
Try going to the directory itself (cd src\Database) and then try this command:

<code>odb -d sqlite -s -q Config.h VMSettings.h</code>

Then it should work.

**Comment by JakeTrock** [comment]
Worked!
